[package]
name = "light-indexer"
edition.workspace = true
version.workspace = true
publish.workspace = true

[[bin]]
name = "light-indexer"
path = "src/main.rs"

[dependencies]
light-indexer-core = { workspace = true }
light-indexer-source = { workspace = true }
light-indexer-storage = { workspace = true }
light-indexer-rpc = { workspace = true }

tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prometheus = { workspace = true }
clap = { workspace = true }
num_cpus = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
