[package]
name = "light-indexer-core"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
figment = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }

tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }
chrono = { workspace = true }
num_cpus = { workspace = true }
